---
- name: Deploy dotfiles
  environment:
    PATH: "{{ dev_brew_path_env }}"
  block:
    - name: Ensure dotfiles repository is cloned locally
      ansible.builtin.git:
        repo: "{{ dev_dotfiles_repo }}"
        dest: "{{ dev_dotfiles_repo_local_destination }}"
        version: "{{ dev_dotfiles_repo_version }}"
        accept_hostkey: "{{ dev_dotfiles_repo_accept_hostkey }}"

    - name: Build directories list
      ansible.builtin.find:
        paths: ["{{ dev_dotfiles_repo_local_destination }}"]
        recurse: false
        file_type: directory
      register: dev_dotfiles_dirs

    - name: Stow dotfiles
      ansible.builtin.command:
        cmd: "stow --no-folding --target='{{ dev_dotfiles_home }}' {{ item.path | basename }} --verbose=2"
        chdir: "{{ dev_dotfiles_repo_local_destination }}"
      loop: "{{ dev_dotfiles_dirs.files }}"
      register: dev_stow_result
      # match any stow --verbose=2 mutation, not just LINK
      changed_when: 'dev_stow_result.stderr is search("(LINK|UNLINK|MKDIR|RMDIR|MOVE): ")'
