---
# install brew
- ansible.builtin.include_tasks: brew.yml
# install packages
- ansible.builtin.include_tasks: packages.yml
# setup default shell
- ansible.builtin.include_tasks: shell.yml
# deploy dotfiles
- ansible.builtin.include_tasks: dotfiles.yml
