---
- name: Install Homebrew
  ansible.builtin.include_tasks: brew.yml

- name: Install packages
  ansible.builtin.include_tasks: packages.yml

- name: Configure default shell
  ansible.builtin.include_tasks: shell.yml

- name: Deploy dotfiles
  ansible.builtin.include_tasks: dotfiles.yml
