---
- name: Install Homebrew
  ansible.builtin.include_tasks: brew.yml

- name: Install brew packages
  ansible.builtin.include_tasks: packages/brew.yml

- name: Install npm packages
  ansible.builtin.include_tasks: packages/npm.yml

- name: Install krew plugins
  ansible.builtin.include_tasks: packages/krew.yml

- name: Install herdr plugins
  ansible.builtin.include_tasks: packages/herdr.yml

- name: Configure default shell
  ansible.builtin.include_tasks: shell.yml

- name: Deploy dotfiles
  ansible.builtin.include_tasks: dotfiles.yml
