---
- name: install brew packages
  community.general.homebrew:
    name:
      # core
      - bash
      - coreutils
      - curl
      - git
      - stow
      - xclip
      - zip
      - zsh
      # shell
      - antidote
      - starship
      # toolchains
      - bazelisk
      - go
      - kcl
      - node
      - python3
      - rustup
      - terraform
      # neovim
      - fd
      - fzy
      - neovim
      - ripgrep
      # tmux
      - tmux
      - tpm
      # dev
      - buildozer
      - ibazel
      - jq
      - pre-commit
      - yq
      # containers
      - docker
      - krew
      - kubectl
      - minikube

- name: install krew plugins
  vars:
    plugins:
      - ctx
      - ns
      - print-env
  environment:
    PATH: "/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.HOME }}/.krew/bin:{{ ansible_env.PATH }}"
  block:
    - name: check if krew default index dir exists
      stat:
        path: "{{ ansible_env.HOME }}/.krew/index/default"
      register: krew_index

    - name: update krew index
      command: kubectl krew update
      when: not krew_index.stat.exists

    - name: get list of installed plugins
      shell: kubectl krew list | cut -f1
      register: installed_plugins
      changed_when: false
      ignore_errors: true

    - name: install krew plugins
      command: "kubectl krew install {{ plugins | difference(installed_plugins.stdout_lines) | join(' ') }}"
      when: plugins | difference(installed_plugins.stdout_lines) | length > 0
