---
- name: install brew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"

- name: install brew formulae
  community.general.homebrew:
    name: "{{ brew_formulae }}"

- name: install brew formulae (macOS only)
  community.general.homebrew:
    name: "{{ brew_formulae_darwin }}"
  when: ansible_facts["os_family"] == 'Darwin'

- name: install krew plugins
  environment:
    PATH: "/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:{{ ansible_facts['env']['HOME'] }}/.krew/bin:{{ ansible_facts['env']['PATH'] }}"
  ignore_errors: true
  block:
    - name: check if krew default index dir exists
      ansible.builtin.stat:
        path: "{{ ansible_facts['env']['HOME'] }}/.krew/index/default"
      register: krew_index

    - name: update krew index
      ansible.builtin.command: kubectl krew update
      when: not krew_index.stat.exists

    - name: get list of installed plugins
      ansible.builtin.shell: kubectl krew list | cut -f1
      register: installed_plugins
      changed_when: false

    - name: install krew plugins
      ansible.builtin.command: "kubectl krew install {{ krew_plugins | difference(installed_plugins.stdout_lines) | join(' ') }}"
      when: krew_plugins | difference(installed_plugins.stdout_lines) | length > 0

- name: install brew casks
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
  when: ansible_facts["os_family"] == 'Darwin'
